#spring.application.name=ycommerce
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/ycommerce?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: yoon
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    #show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: khsso102649@gmail.com
    password: yjuikbjezgbyosyw
    properties:
      mail:
        smtp:
          auth: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
    auth-code-expiration-millis: 180000

  data:
    redis:
      host: localhost
      port: 6379






logging:
  level:
    org.hibernate.SQL: debug


jwt:
  secret: berryafteryooneverstopworkingdeveloperzzzddddddd

secret:
  AES256: berry96afteryoon

